name: "ci-skip-detection"
description: "it takes all the commits of a push and it says if we skip or not the workflow run"

inputs:
  token:
    description: "It's the github classic token that has the right of your repository"
    required: true
runs:
  using: "composite"
  steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout external action repo
      uses: actions/checkout@v2
      with:
        repository: 'AdamBoukhari/ci-skip-action' 

    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Get commit messages via API
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        MESSAGES=$(python scripts/get_commits.py "${{ github.event.before }}" "${{ github.sha }}")
        echo "messages=$MESSAGES" >> $GITHUB_ENV
      shell: bash

    - name: Verif
      run: echo "$messages" | sed 's/%0A/\n/g'
      shell: bash

    - name: Write commit messages to file
      run: echo "$messages" | sed 's/%0A/\n/g' > commit_messages.txt
      shell: bash
 
    - name: Create result file
      run: touch $(pwd)/result.txt
      shell: bash
  
    - name: Build and run Docker container
      run: |
        docker build -t my-ia-image -f docker/DOCKERFILE .
        docker run -v $(pwd)/commit_messages.txt:/app/commit_messages.txt -v $(pwd)/result.txt:/app/result.txt my-ia-image
      shell: bash
 
    - name: Determine if we should skip subsequent jobs
      id: check_skip
      run: |
        result=$(cat result.txt)
        echo $result
        if [[ "$result" == "skip" ]]; then
            echo "SKIP=1" >> $GITHUB_ENV
        else
            echo "SKIP=0" >> $GITHUB_ENV 
        fi
      shell: bash

 